CLASS zbp_054906_traveltp DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF zr_054906_traveltp.
  PROTECTED SECTION.

  PRIVATE SECTION.
ENDCLASS.


CLASS zbp_054906_traveltp IMPLEMENTATION.
ENDCLASS.
